 const SKILL_SUGGESTIONS = [
  "JavaScript",
  "React",
  "Node.js",
  "Python",
  "TypeScript",
  "Next.js",
  "Vue.js",
  "Angular",
  "PHP",
  "Laravel",
  "WordPress",
  "Shopify",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Bootstrap",
  "UI/UX Design",
  "Figma",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Graphic Design",
  "Content Writing",
  "Copywriting",
  "SEO",
  "Digital Marketing",
  "Social Media Marketing",
  "Data Analysis",
  "Machine Learning",
  "AI",
  "Database Design",
  "MySQL",
  "PostgreSQL",
  "Mobile Development",
  "React Native",
  "Flutter",
  "iOS",
  "Android",
  "Swift",
  "Kotlin",
]
const CATEGORIES = [
  "Web Development",
  "Mobile Development",
  "UI/UX Design",
  "Graphic Design",
  "Content Writing",
  "Digital Marketing",
  "Data Science",
  "DevOps",
  "E-commerce",
  "WordPress",
  "SEO",
  "Social Media",
  "Video Editing",
  "Photography",
  "Translation",
  "Virtual Assistant",
  "Consulting",
  "Other",
]


export { CATEGORIES,SKILL_SUGGESTIONS}